ADUM/Controllers/AddController.cs
using ADUM.Models;
using ADUM.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADUM.Controllers
{
    public class AddController : Controller
    {
        private readonly IAddRepository _addRepository;

        public AddController(IAddRepository addRepository)
        {
            _addRepository = addRepository;
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Token token)
        {
            // CHECK IF FORM IS EMPTY
        if(ModelState.IsValid)
            {
                _addRepository.CreateToken(token);
                return RedirectToAction("ConfirmCreate");
            }
        else
            {
                return View();
            }

        }

        public IActionResult ConfirmCreate()
        {
            return View();
        }

    }
}

ADUM/Controllers/TokenController.cs
using ADUM.Repository;
using ADUM.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADUM.Controllers
{
    public class TokenController : Controller
    {
        private readonly ITokenRepository _tokenRepository;

        public TokenController(ITokenRepository tokenRepository)
        {
            _tokenRepository = tokenRepository;
        }
        
        public IActionResult List()
        {
            var tokenListViewModel = new TokenListViewModel();
            //var tokens = _tokenRepository.GetAllTokens();
            tokenListViewModel.Tokens = _tokenRepository.GetAllTokens();
            return View(tokenListViewModel);
        }

        public IActionResult Past()
        {
            var tokenListViewModel = new TokenListViewModel();
            tokenListViewModel.Tokens = _tokenRepository.GetAllTokens();
            return View(tokenListViewModel);
        }

    }
}

ADUM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AVASAD - ADUM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site2.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ADUM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Add" asp-action="Add">Add Access</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Token" asp-action="List">Current Access</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Token" asp-action="Past">Past Access</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            AVASAD - 2021 &copy; All rights reserved
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>